### ISSUE TITLE
Cant get it running

### ISSUE THREAD

**Issue by sajov** [go4ble/hermes-respeaker-pixel-ring#2]
Hi, thank you very much for your work! This is exactly  what i was searching for.

System:
Raspberry PI3+
Description:	Raspbian GNU/Linux 11 (bullseye)
Release:	11
Codename:	bullseye

docker run --rm -it \
  --device /dev/spidev0.0 \
  --device /dev/spidev0.1 \
  --device /dev/gpiomem \
  -e HOST=192.168.0.67 \
  -e PORT=1883 \
  -e SITE_ID=rhasspy-sat-II \
  go4ble/hermes-respeaker-pixel-ring:latest
/usr/local/lib/python3.10/site-packages/gpiozero/devices.py:288: PinFactoryFallback: Falling back from rpigpio: No module named 'RPi'
  warnings.warn(
/usr/local/lib/python3.10/site-packages/gpiozero/devices.py:288: PinFactoryFallback: Falling back from lgpio: No module named 'lgpio'
  warnings.warn(
/usr/local/lib/python3.10/site-packages/gpiozero/devices.py:288: PinFactoryFallback: Falling back from rpio: No module named 'RPIO'
  warnings.warn(
/usr/local/lib/python3.10/site-packages/gpiozero/devices.py:288: PinFactoryFallback: Falling back from pigpio: No module named 'pigpio'
  warnings.warn(
/usr/local/lib/python3.10/site-packages/gpiozero/devices.py:285: NativePinFactoryFallback: Falling back to the experimental pin factory NativeFactory because no other pin factory could be loaded. For best results, install RPi.GPIO or pigpio. See https://gpiozero.readthedocs.io/en/stable/api_pins.html for more information.
  warnings.warn(NativePinFactoryFallback(native_fallback_message))
Connected with result code 0

I'm not a familiar with python, installing `rpi.gpio` did not helped.
Following gpiozero instructions did not helped.
Any suggestions?
Thanks

**Comment by go4ble** [comment]
Hello! I appreciate your interest in this project.

Are you using the gpio or usb pixel ring? I have only tested this on Ubuntu with pi3 and gpio. 

I would recommend also taking a look at https://github.com/respeaker/pixel_ring, as it is the basis for this project. It would be interesting if you can get the examples from there working.

**Comment by sajov** [comment]
I also use the gpio.
The respeaker pixel_ring example is running.
I tested to install all requirements on Host System and start your Script with the Same result

**Comment by go4ble** [comment]
My next suggestion was going to be to try docker build, for the current image at hub.docker.com is a linux/arm64 build. However, it sounds like docker isn't the issue as you have tried to run it without and get the same result.
Unfortunately, python is also unfamiliar to me and I'm not sure how to interpret the error message.
The dockerfile runs this command `apk add build-base linux-headers`. I wonder if there is something important from one of those Alpine packages (but instead from the Raspbian equivalent).

**Comment by sajov** [comment]
So i had progress.
Your script is working if exceuted, it connect mqtt and led's responding. 
I tried balenalib/raspberry-pi-alpine-python:latest and got the same PinFactoryFallback warnings but IT IS WORKING :-)
I will try you image again because im guessing i did something wrong. i will let you know then.
Cheers

**Comment by sajov** [comment]
Working fine
